### PR TITLE
enable dependabot

### PR DESCRIPTION
**Pull request by nhojpatrick**

### CODE REVIEW

**Comment by garydgregory** [comment]
It does not make sense to have dependabot without a github build IMO, this should be done like the other Commons components that use the default Maven goal.

**Comment by nhojpatrick** [comment]
> It does not make sense to have dependabot without a github build IMO, this should be done like the other Commons components that use the default Maven goal.

@garydgregory lots of the other commons project are using dependabot, it also can just create a branch containing the updates and then other cicd spot those branches and build them. You don't have to force yourself into have a GitHub vendor lock in. If it was my choice, Commons would be using Renovate running on Apache Infrastructure and Apache Jenkins Farm and just have GitHub for Source Code and PR's.

**Comment by rmannibucau** [comment]
From what i see, dependabot has more false positives than benefits, in particular for commons projects so not sure it makes sense to bulk enable it like that.

Upgrades are often a prerelease review task where project knowledge helps to pick relevant ones only.

Just my 2 cts

**Comment by sebbASF** [comment]
Agreed.

There are often several dependency updates between releases.
With dependabot, each one is treated separately, instead of doing them all at the same time.

That's a waste of time and resources, clogging up the mailing lists.

**Comment by garydgregory** [comment]
I like Dependabot but I've only enabled it for the components I care about.

There has been discussion of having a separate list for bots to send
message, which some fuzzing service could also use.

Gary

**Pull request closed without merging**
