### PR TITLE
JUnit v4.13.2

### PR DESCRIPTION
**Pull request by nhojpatrick**
Upgrade to JUnit v4.13.1

### CODE REVIEW

**Comment by kinow** [comment]
Closed/re-opened to trigger Travis CI.

**Comment by nhojpatrick** [comment]
@garydgregory so dependabot has detected v4.13.1 is available but appears to have failed to detect v4.13.2 is available.

**Comment by garydgregory** [comment]
Dependabot will find the dependency but only once one of its 5 PR slots opens up.

**Comment by nhojpatrick** [comment]
JUnit v4.13.1 PR by dependabot appears to have been created as https://github.com/apache/commons-weaver/pull/9 but it doesn't appear to have picked up v4.13.2 and superseded v4.13.1 with a pr for v4.13.2.

**Pull request closed without merging**
