### PR TITLE
hamcrest v2.2

### PR DESCRIPTION
**Pull request by nhojpatrick**
Upgrade to hamcrest v2.2 from v1.3

### CODE REVIEW

**Comment by nhojpatrick** [comment]
Build failure due to this travis error around the distribution. It's downloading snapshots, but won't the artifacts it needs be in a local repo? Otherwise what happens when multiple builds are happening at once?

```
[INFO] -----------------< org.apache.commons:commons-weaver >------------------
[INFO] Building Apache Commons Weaver Distribution 2.1-SNAPSHOT         [12/12]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] Downloading from apache-snapshots: https://repository.apache.org/snapshots/org/apache/commons/commons-weaver-processor/2.1-SNAPSHOT/maven-metadata.xml
[INFO] Downloading from apache-snapshots: https://repository.apache.org/snapshots/org/apache/commons/commons-weaver-privilizer-api/2.1-SNAPSHOT/maven-metadata.xml
[INFO] Downloading from apache-snapshots: https://repository.apache.org/snapshots/org/apache/commons/commons-weaver-privilizer/2.1-SNAPSHOT/maven-metadata.xml
[INFO] Downloading from apache-snapshots: https://repository.apache.org/snapshots/org/apache/commons/commons-weaver-normalizer/2.1-SNAPSHOT/maven-metadata.xml
[INFO] Downloading from apache-snapshots: https://repository.apache.org/snapshots/org/apache/commons/commons-weaver-maven-plugin/2.1-SNAPSHOT/maven-metadata.xml
[INFO] Downloading from apache-snapshots: https://repository.apache.org/snapshots/org/apache/commons/commons-weaver-antlib/2.1-SNAPSHOT/maven-metadata.xml
[INFO] Downloading from sonatype-snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/apache/commons/commons-weaver-privilizer-api/2.1-SNAPSHOT/commons-weaver-privilizer-api-2.1-SNAPSHOT-javadoc.jar
[INFO] Downloading from sonatype-snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/apache/commons/commons-weaver-processor/2.1-SNAPSHOT/commons-weaver-processor-2.1-SNAPSHOT-javadoc.jar
[INFO] Downloading from sonatype-snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/apache/commons/commons-weaver-privilizer/2.1-SNAPSHOT/commons-weaver-privilizer-2.1-SNAPSHOT-javadoc.jar
[INFO] Downloading from sonatype-snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/apache/commons/commons-weaver-normalizer/2.1-SNAPSHOT/commons-weaver-normalizer-2.1-SNAPSHOT-javadoc.jar
[INFO] Downloading from sonatype-snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/apache/commons/commons-weaver-maven-plugin/2.1-SNAPSHOT/commons-weaver-maven-plugin-2.1-SNAPSHOT-javadoc.jar
[INFO] Downloading from sonatype-snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/apache/commons/commons-weaver-antlib/2.1-SNAPSHOT/commons-weaver-antlib-2.1-SNAPSHOT-javadoc.jar
[INFO] Downloading from apache-snapshots: https://repository.apache.org/snapshots/org/apache/commons/commons-weaver-processor/2.1-SNAPSHOT/commons-weaver-processor-2.1-SNAPSHOT-javadoc.jar
[INFO] Downloading from apache-snapshots: https://repository.apache.org/snapshots/org/apache/commons/commons-weaver-privilizer/2.1-SNAPSHOT/commons-weaver-privilizer-2.1-SNAPSHOT-javadoc.jar
[INFO] Downloading from apache-snapshots: https://repository.apache.org/snapshots/org/apache/commons/commons-weaver-privilizer-api/2.1-SNAPSHOT/commons-weaver-privilizer-api-2.1-SNAPSHOT-javadoc.jar
[INFO] Downloading from apache-snapshots: https://repository.apache.org/snapshots/org/apache/commons/commons-weaver-normalizer/2.1-SNAPSHOT/commons-weaver-normalizer-2.1-SNAPSHOT-javadoc.jar
[INFO] Downloading from apache-snapshots: https://repository.apache.org/snapshots/org/apache/commons/commons-weaver-maven-plugin/2.1-SNAPSHOT/commons-weaver-maven-plugin-2.1-SNAPSHOT-javadoc.jar
[INFO] Downloading from apache-snapshots: https://repository.apache.org/snapshots/org/apache/commons/commons-weaver-antlib/2.1-SNAPSHOT/commons-weaver-antlib-2.1-SNAPSHOT-javadoc.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Apache Commons Weaver 2.1-SNAPSHOT:
[INFO] 
[INFO] Apache Commons Weaver .............................. SUCCESS [ 13.941 s]
[INFO] Apache Commons Weaver Build Tools .................. SUCCESS [  2.122 s]
[INFO] Apache Commons Weaver Parent ....................... SUCCESS [  2.070 s]
[INFO] Apache Commons Weaver Processor .................... SUCCESS [  9.997 s]
[INFO] Apache Commons Weaver Maven Plugin ................. SUCCESS [  7.065 s]
[INFO] Apache Commons Weaver Antlib ....................... SUCCESS [  4.529 s]
[INFO] Apache Commons Weaver Modules aggregator project ... SUCCESS [  0.600 s]
[INFO] Apache Commons Weaver Privilizer Parent POM ........ SUCCESS [  0.561 s]
[INFO] Apache Commons Weaver Privilizer API ............... SUCCESS [  2.511 s]
[INFO] Apache Commons Weaver Privilizer Weaver ............ SUCCESS [ 20.172 s]
[INFO] Apache Commons Weaver Normalizer ................... SUCCESS [  4.485 s]
[INFO] Apache Commons Weaver Distribution ................. FAILURE [  3.089 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:12 min
[INFO] Finished at: 2020-10-13T07:21:49Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project commons-weaver: Could not resolve dependencies for project org.apache.commons:commons-weaver:pom:2.1-SNAPSHOT: The following artifacts could not be resolved: org.apache.commons:commons-weaver-processor:jar:javadoc:2.1-SNAPSHOT, org.apache.commons:commons-weaver-privilizer-api:jar:javadoc:2.1-SNAPSHOT, org.apache.commons:commons-weaver-privilizer:jar:javadoc:2.1-SNAPSHOT, org.apache.commons:commons-weaver-normalizer:jar:javadoc:2.1-SNAPSHOT, org.apache.commons:commons-weaver-maven-plugin:jar:javadoc:2.1-SNAPSHOT, org.apache.commons:commons-weaver-antlib:jar:javadoc:2.1-SNAPSHOT: Could not find artifact org.apache.commons:commons-weaver-processor:jar:javadoc:2.1-SNAPSHOT in sonatype-snapshots (https://oss.sonatype.org/content/repositories/snapshots/) -> [Help 1]
```

**Comment by garydgregory** [comment]
@nhojpatrick
Please stop creating pull requests for version updates, we have Dependabot
for that. If a component you care about does not support Dependabot, then
provide a PR that adds Dependabot.
TY!

**Comment by nhojpatrick** [comment]
@garydgregory As I noticed junit v4.13.1 had been released, I raised PR's
for every commons repo that was still using v4.x. Any repo where a
subsequent dependabot pr was raised for the same version, I subsequently
deleted my PR.

I did notice some commons projects were still using v4.10, 4.11 and 4.12,
so obviously dependabot isn't running for these.

I also noticed several commons projects where the master branch doesn't
build locally or pr fail to build on travis due to unrelated issues where I
added a comment on the pr about that issue.

From my view of a commons project I've no idea if Dependabot is running for
a given git repo. It might be that maintainers have chosen to
explicitly disable Dependabot. I also wasn't aware dependabot could be
enabled via a PR, I thought you had to go to Settings -> Security &
Analysis -> Dependabot alerts -> Enable.

Regarding hamcrest specifically, the artifacts have been refactored and
junit v4.x depends upon the older v1.x version. The artifacts
hamcrest-core, hamcrest-all and hamcrest-library were all circa 2018 when
v2.x was released, and replaced with simply hamcrest. So I wouldn't expect
Dependabot to upgrade hamcrest from v1.x to v2.x correctly without manual
intervention.

Also the error I've listed in this PR would happen for any PR raised,
irrespective if it was Dependabot or Human raising the PR. So you'll see
the same error if someone enabled Dependabot for commons-weaver for this
change.

John

**Comment by nhojpatrick** [comment]
@garydgregory so dependabot has still not detected hamcrest v2.2 is available and is still stuck on v1.3, so trying to get merged in again.

**Pull request closed without merging**
